version: "{branch} {build}"

max_jobs: 1

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build:
  verbosity: detailed

before_build:
  - ECHO %APPVEYOR_REPO_TAG_NAME%

build_script:
  - IF DEFINED APPVEYOR_REPO_TAG_NAME ( gradlew.bat buildByVersion -PVERSION=%APPVEYOR_REPO_TAG_NAME% )
  - gradlew.bat build --info --no-daemon
  - gradlew.bat createAllExecutables
  - gradlew.bat sign
  - ls -al build/launch4j/
  - pwd

after_build:
  - cp build/launch4j/ffc-airsync.exe ffc-airsync.exe
  - 7z a -mx9 ffc-airsync.zip ffc-airsync.exe
cache:
  - .gradle

matrix:
  fast_finish: true

artifacts:
  - path: build/launch4j/ffc-airsync.exe
    name: ffc-airsync client
    type: File

  - path: ffc-airsync.zip
    name: ffc-airsync zip client
    type: File

deploy:
  description: 'โปรแกรม ffc-airsync'
  provider: GitHub
  auth_token:
    secure: q3WgoVWpklbGnGcjjS7g8QKNDoD6roJ7PY+BDWFg4I2h5CC9QdCjhd5MM3HSlRPz
  artifact: /.*/
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
