version: "{branch} {build}"

max_jobs: 1

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build:
  verbosity: detailed

build_script:
  - gradlew.bat jar
  - gradlew.bat createAllExecutables
  - ls -al build/launch4j/

test_script:
  - gradlew.bat check --info --no-daemon

cache:
  - C:\Users\appveyor\.gradle

matrix:
  fast_finish: true

deploy:
  release: $(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: %githubtoken% # your encrypted token from GitHub
  artifact: build/launch4j/.*exe            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
