version: "{branch} {build}"

max_jobs: 1

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build:
  verbosity: detailed

before_build:
  - ECHO %APPVEYOR_REPO_TAG_NAME%

build_script:
  - gradlew.bat build --info --no-daemon
  - ls -al build/launch4j/
  - pwd

after_build:
  - cp build/launch4j/ffc-airsync.exe ffc-airsync.exe
  - 7z a -mx9 ffc-airsync.zip ffc-airsync.exe
cache:
  - .gradle

matrix:
  fast_finish: true

artifacts:
  - path: build/launch4j/ffc-airsync.exe
    name: ffc-airsync launcher
    type: File

  - path: build/launch4j/ffc-airsync-installer.exe
    name: ffc-airsync installer
    type: File

  - path: ffc-airsync.zip
    name: ffc-airsync zip client
    type: File

deploy:
  description: 'โปรแกรม ffc-airsync'
  provider: GitHub
  auth_token:
    secure: dWjuqn4J0wP5jdlmCoQarOTjy1Bt9UHNaBdzSoz8DsJf7XhZx0/4QIJX4Nmexo5t
  artifact: /.*/
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
