version: "{branch} {build}"

max_jobs: 1

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build:
  verbosity: detailed

build_script:
  - gradlew.bat build --info --no-daemon
  - gradlew.bat createAllExecutables
  - ls -al build/launch4j/
  - pwd

cache:
  - .gradle

matrix:
  fast_finish: true

deploy:
  description: 'FFC airsync...'
  provider: GitHub
  auth_token:
    secure: q3WgoVWpklbGnGcjjS7g8QKNDoD6roJ7PY+BDWFg4I2h5CC9QdCjhd5MM3HSlRPz
  artifact: /c/projects/airsynclauncher/build/launch4j/ffc-airsync.exe
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
