version: "{branch} {build}"

max_jobs: 1

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build:
  verbosity: detailed

build_script:
  - gradlew.bat jar
  - gradlew.bat createAllExecutables
  - ls -al build/launch4j/

test_script:
  - gradlew.bat check --info --no-daemon

cache:
  - C:\Users\appveyor\.gradle -> cleanup-cache.txt

matrix:
  fast_finish: true

deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: q3WgoVWpklbGnGcjjS7g8QKNDoD6roJ7PY+BDWFg4I2h5CC9QdCjhd5MM3HSlRPz
  artifact: build/launch4j/*.exe
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
