version: "{branch} {build}"

max_jobs: 1

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build:
  verbosity: detailed

before_build:
  - ECHO %tag%

build_script:
  - IF DEFINED tag (gradlew.bat buildByVersion -PVERSION=$(tag))
  - gradlew.bat build --info --no-daemon
  - gradlew.bat createAllExecutables
  - ls -al build/launch4j/
  - pwd
after_build:
  - mv build/launch4j/ffc-airsync.exe ffc-airsync.exe

cache:
  - .gradle

matrix:
  fast_finish: true

deploy:
  description: 'โปรแกรม ffc-airsync'
  provider: GitHub
  auth_token:
    secure: q3WgoVWpklbGnGcjjS7g8QKNDoD6roJ7PY+BDWFg4I2h5CC9QdCjhd5MM3HSlRPz
  artifact: ffc-airsync.exe
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
