package ffc.airsync.launcher;

import javax.swing.*;
import java.awt.*;

public class SplashScreen {
    public JPanel panel;
    public JProgressBar progressBar;
    public JLabel progressText;
    public JLabel progressTitle;
    public JLabel versionLabel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel.add(panel1, BorderLayout.SOUTH);
        progressBar = new JProgressBar();
        progressBar.setMinimum(0);
        panel1.add(progressBar);
        progressText = new JLabel();
        progressText.setText("Label");
        panel1.add(progressText);
        progressTitle = new JLabel();
        progressTitle.setText("Label");
        panel.add(progressTitle, BorderLayout.CENTER);
        versionLabel = new JLabel();
        versionLabel.setText("Label");
        panel.add(versionLabel, BorderLayout.NORTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
