/*
 * Copyright 2019 NSTDA
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 */
package ffc.airsync.launcher;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;

/**
 * @author piruin
 */
public class SplashPanel extends javax.swing.JPanel {

    private Image backgroud;
    private Font font;

    /**
     * Creates new form SplashPanel
     */
    public SplashPanel() throws IOException, FontFormatException {
        ClassLoader classLoader = getClass().getClassLoader();
        backgroud = new ImageIcon(classLoader.getResource("bg/720p.jpg")).getImage();
        font = Font.createFont(Font.TRUETYPE_FONT, classLoader.getResource("font/Kanit-Light.ttf").openStream()).deriveFont(12f);
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(backgroud, 0, 0, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        versionText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(76, 189, 148));
        setMaximumSize(new java.awt.Dimension(720, 450));
        setPreferredSize(new java.awt.Dimension(720, 450));

        progressBar.setBackground(new Color(0,0,0,0));
        progressBar.setForeground(new java.awt.Color(255, 255, 255));
        progressBar.setBorderPainted(false);
        progressBar.setDoubleBuffered(true);
        progressBar.setPreferredSize(new java.awt.Dimension(146, 8));
        progressBar.setRequestFocusEnabled(false);

        versionText.setBackground(new java.awt.Color(0, 0, 0));
        versionText.setFont(font);
        versionText.setForeground(new java.awt.Color(255, 255, 255));
        versionText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        versionText.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(159, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(versionText))
                    .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(versionText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JProgressBar progressBar;
    protected javax.swing.JLabel versionText;
    // End of variables declaration//GEN-END:variables
}
